<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5D9A7RR" failures="1" tests="7" name="Smoke" time="6.568" errors="0" timestamp="2022-02-22T13:25:27 EST">
  <testcase classname="com.api.jobs.requests.Jobs_PUT" name="updateJob" time="2.941"/>
  <testcase classname="com.api.jobs.requests.Jobs_PUT" name="updateJob" time="0.212"/>
  <testcase classname="com.api.jobs.requests.Jobs_DELETE" name="delete_Job_id" time="0.154"/>
  <testcase classname="com.api.jobs.requests.Jobs_DELETE" name="delete_Job_id" time="0.158"/>
  <testcase classname="com.api.jobs.requests.Jobs_GET" name="getallJobs" time="0.171"/>
  <testcase classname="com.api.jobs.requests.Jobs_POST" name="createJob" time="0.305"/>
  <testcase classname="com.api.jobs.requests.Jobs_POST" name="createJob" time="0.208">
    <failure type="java.lang.AssertionError" message="expected [409] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [409] but found [200]
at com.api.jobs.requests.Jobs_POST.createJob(Jobs_POST.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- createJob -->
</testsuite> <!-- Smoke -->
